routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Posts\CommentController;

use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Middleware\logMiddleware;
use App\Http\Controllers\BusketController;

use App\Http\Controllers\RegisterController;
use App\Http\Controllers\TestController;
use App\Http\Middleware\tokenMiddleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Testing\TestComponent;

Route::name('user.')->group(function(){
    Route::get('/user',[UserController::class,'index'])->name('user.index');
    Route::get('/user/show/{user}',[UserController::class,'show'])->middleware('auth')->name('show');

route::get('/login',function(){

    if(Auth::check())
    {
        return redirect(route('user.show'));
    }
    return view('login.index');
})->name('login');



});



Route::get('/', 'HomeController@index');
Route::post('/home/{produts}', [HomeController::class,'show'])->name('home.show');
//Route::get('/user/', [UserController::class,'index'])->name('user.index');
//Route::get('/user/show/{user}',  [UserController::class,'show'])->name('user.show');

Route::get('/busket', 'BusketController@index')->name('busket');
Route::post('busket/{busket}', [BusketController::class,'store'])->name('busket.store');
Route::get('busket/{busket}', [BusketController::class,'show'])->name('busket.show');


Route::get('register',[RegisterController::class,'index'])->name('register.index');
Route::post('register/store',[RegisterController::class,'store'])->name('register.store');
//Route::get('login', [LoginController::class,'index'])->name('login.index');
Route::get('login/search', [LoginController::class,'search'])->name('login.search');

Route::get('post','PostController@index');
Route::get('post/search', [PostController::class,'search'])->name('post.search');
Route::post('post/store', [PostController::class,'store'])->name('post.store');
Route::get('post/create', [PostController::class,'create'])->name('post.create');
Route::get('post/show/{post}', [postController::class,'show'])->name('post.show');


Route::get('/about', 'AboutController@index');


Route::get('contact', 'ContactController@index')->name('Contact');


Route::get('test',[TestController::class,'index'])->name('test');

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class LoginController extends Controller
{
    public function index()
    {
        return view ('login.index');
    }

    public function store(Request $request)
    {
        
    }
    protected function search(Request $request)
    {   
        $user_mail=$request->email;  
        $user_password=$request->password; 

        $user=User::query()->get(['email','password'])->where('email',$user_mail);
       
        if($user->value('password')===$user_password)
        {
            alert(__('You login with success')); 
            $user_id=$user->value('email');
             return redirect('/user/show/'.$user_id);
         }
        else
        {
            wrong(__('Something went wrong'));
            return redirect('/login');
        }

    }
}
 

resources/views/login/index.blade.php
@extends('layouts.base')
@section('page.title') Login Page @endsection

@section('content')
    <x-container>
        <div class="row justify-content-center">
            <div class="col col-md-4 col-sm-6 ">
                <!-- Form for registration-->
            <x-card.wrapper>
                <x-card.body action="{{route('login.search')}}">
                    <x-card.title>{{ __('Login')}}</x-card.title>                       
                    <x-label for="">{{__('Email')}}</x-label>
                    <x-input name="email" required></x-input><br>
                    <x-label for="">{{__('Password')}}</x-label>
                    <x-input name="password" required></x-input><br>                
                    <x-card.action>
                        <x-button>{{_('Login')}}</x-button>
                        <x-a-link href="{{route('register.index')}}">
                            Register
                        </x-a-link>
                    </x-card.action>
                </x-card.body>
            </x-card.wrapper>
            </div>
        </div>        
    </x-container>
@endsection

resources/views/login/register.blade.php
@extends('layouts.base')
@section('page.title') Registration @endsection

@section('content')
<x-container>
    <div class="row  justify-content-center">
        <div class="col col-md-4  col-sm-6">
            <x-card.wrapper> 
                <x-card.body action="{{route('register.store')}}" method="post">
                    <x-card.title>{{ __('Registration')}}</x-card.title>
                    <x-label for="name" >{{__('First Name')}}</x-label>
                    <x-input name="name" required /><br>
                    <x-label for="sname" >{{__('Second Name')}}</x-label>
                    <x-input name="sname" required /><br>
                    <x-form.item > 
                        <x-label  for="genderM">
                            {{__('Male')}}
                            <input required type="radio" id="genderM"/> 
                        </x-label>
                        <x-label for="genderF">
                            {{__('Female')}}
                            <input required type="radio" id="genderF" />
                    </x-label>
                    </x-form.item>
                    <x-label for="date"  >{{__('Birthday')}}</x-label>
                    <x-input type="date" name="date" required /><br>
                    <x-label for="email"  >{{__('Email')}}</x-label>
                    <x-input name="email" required /><br>
                    <x-label for="confirm_Email"  >{{__('Confirm Email')}}</x-label>
                    <x-input name="confirm_Email"  required/><br>
                    <x-label for="password"  >{{__('Password')}}</x-label>
                    <x-input name="password"  type="password" required /><br>
                    <x-label for="avatar"  >{{__('Avatar')}}</x-label>
                    <x-input name="avatar"  type="file"  /><br>
                    <x-checkbox name='accept' checked >{{__('I accept')}}</x-checkbox>
               <x-card.action>
                    <x-a-link href="{{route('user.login')}}">{{__('Back')}}</x-a-link>
                    <x-button >{{__('Register')}}</x-button>
                </x-card.action>  
            </x-card.body> 
            </x-card.wrapper>   
        </div>    
    </div> 
</x-container>

@push('js')
<script src='/js/checkbox.js'></script>
    
@endpush

@endsection